//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Rpt_ReportSettings
    {
        public int ReportSettingID { get; set; }
        public string ReportHeader { get; set; }
        public string ReportFooter { get; set; }
        public byte[] ReportPicture { get; set; }
        public Nullable<bool> ShowPrintedBy { get; set; }
        public Nullable<bool> ShowPrintDate { get; set; }
        public Nullable<bool> ShowReportPicture { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> InactivationUserID { get; set; }
        public Nullable<System.DateTime> InactivationDate { get; set; }
        public string FacRptTitleA4 { get; set; }
        public string FacRptTitleA5 { get; set; }
        public string FacRptTitleA6 { get; set; }
        public Nullable<bool> AlternateRowColore { get; set; }
        public Nullable<int> FacRptPointUnit1QuantityMoreThan { get; set; }
        public Nullable<int> FacRptPointUnit1QuantityLessThan { get; set; }
        public Nullable<int> FacRptPageSize { get; set; }
        public Nullable<int> FacRptAutoPageSizeA4MoreThan { get; set; }
        public Nullable<int> FacRptAutoPageSizeA5LessThan { get; set; }
        public Nullable<int> FacRptAutoPageSizeA6LessThan { get; set; }
        public Nullable<bool> FacRptShowPointUnit1QuantityLessThan { get; set; }
        public Nullable<bool> FacRptShowPointUnit1QuantityMoreThan { get; set; }
        public Nullable<bool> FacCheckReplicaPrint { get; set; }
        public Nullable<bool> FacShowReplicaInPrint { get; set; }
        public Nullable<bool> FacShowFactorPrintDescriptionInReplica { get; set; }
        public Nullable<bool> FacShowReportPictrue { get; set; }
        public Nullable<bool> PrintPreView { get; set; }
        public Nullable<bool> FacPrintPreView { get; set; }
        public string Username { get; set; }
        public string Fullname { get; set; }
        public Nullable<bool> ShowReportHeader { get; set; }
        public Nullable<bool> ShowReportFooter { get; set; }
        public Nullable<bool> FacRptPrintPreView { get; set; }
        public Nullable<bool> ShowEconomicCode { get; set; }
    }
}
