//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sec_Current_User
    {
        public long CurrentUserID { get; set; }
        public long FK_UerID { get; set; }
        public string UserName { get; set; }
    
        public virtual tbl_Sec_Users tbl_Sec_Users { get; set; }
    }
}
