//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_geo_Location
    {
        public int LocationID { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<int> Fk_FieldID { get; set; }
        public Nullable<int> Fk_BuildingID { get; set; }
        public Nullable<int> Fk_WarehouseID { get; set; }
        public Nullable<int> Fk_WaterStorageID { get; set; }
        public Nullable<int> Fk_WaterID { get; set; }
        public Nullable<int> Fk_WaterTransmissionLineID { get; set; }
        public Nullable<int> Fk_PartID { get; set; }
    }
}
