//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cmn_Business
    {
        public int BusinessID { get; set; }
        public string NameEn { get; set; }
        public string NameFa { get; set; }
        public Nullable<int> Fk_BusinessCategoryID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
