//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Setting_Version
    {
        public int VersionID { get; set; }
        public System.DateTime VersionDate { get; set; }
        public string VersionDescription { get; set; }
        public string VersionNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
