//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_src_Land
    {
        public int LandID { get; set; }
        public Nullable<decimal> UsableArea { get; set; }
        public Nullable<decimal> TotalArea { get; set; }
        public Nullable<int> Fk_SoilTextureID { get; set; }
        public Nullable<int> Fk_OwnershipID { get; set; }
        public Nullable<int> Fk_FieldUseTypeID { get; set; }
        public Nullable<int> Fk_ProvinceID { get; set; }
        public Nullable<int> Fk_TownshipID { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> InactivationUserID { get; set; }
        public Nullable<System.DateTime> InactivationDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> Fk_partID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Opposition { get; set; }
        public string Code { get; set; }
        public string DocNumber { get; set; }
        public Nullable<bool> Salability { get; set; }
        public Nullable<bool> changeUse { get; set; }
        public string FutureProgram { get; set; }
        public string DocPlace { get; set; }
        public System.Data.Spatial.DbGeometry Location { get; set; }
        public string Name { get; set; }
    }
}
