//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cmn_Document
    {
        public int DocumentID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Document { get; set; }
        public Nullable<int> Fk_CompanyID { get; set; }
        public Nullable<int> Fk_CollectionID { get; set; }
        public Nullable<int> Fk_SubcollectionID { get; set; }
        public Nullable<int> Fk_PartID { get; set; }
        public Nullable<int> Fk_FieldID { get; set; }
        public Nullable<int> Fk_WarehouseID { get; set; }
        public Nullable<int> Fk_BuildingID { get; set; }
        public Nullable<int> Fk_MachineryID { get; set; }
        public Nullable<int> Fk_WaterID { get; set; }
        public Nullable<int> Fk_WaterStorageID { get; set; }
        public Nullable<int> Fk_WaterTransmissionLineID { get; set; }
        public Nullable<int> Fk_TreeID { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> InactivationUserID { get; set; }
        public Nullable<System.DateTime> InactivationDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> Fk_LandID { get; set; }
    }
}
