//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sec_Items_Users_Link
    {
        public int ItemUserID { get; set; }
        public long FK_UserID { get; set; }
        public int FK_ItemID { get; set; }
        public bool HasWrite { get; set; }
        public Nullable<bool> bitSave { get; set; }
        public Nullable<bool> bitChange { get; set; }
        public Nullable<bool> bitDelete { get; set; }
        public Nullable<bool> bitNew { get; set; }
        public Nullable<bool> bitPrint { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
