//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sec_Items
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public byte[] ItemLogo { get; set; }
        public int OrderInLevel { get; set; }
        public int FK_PackageID { get; set; }
        public string RelatedFormName { get; set; }
        public Nullable<bool> EnableOnExplorerBar { get; set; }
    }
}
