//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sec_Shops
    {
        public tbl_Sec_Shops()
        {
            this.tbl_Sec_Users = new HashSet<tbl_Sec_Users>();
        }
    
        public int ShopID { get; set; }
        public string ShopName { get; set; }
        public Nullable<int> ShopCode { get; set; }
        public string EconomicCode { get; set; }
        public string PostalCode { get; set; }
        public string ShopAbbr { get; set; }
        public byte[] ShopLogo { get; set; }
        public string ShopAddress { get; set; }
        public string ShopTell { get; set; }
        public string ShopTell1 { get; set; }
        public string ShopTell2 { get; set; }
        public string ShopFax { get; set; }
        public string ShopMobile { get; set; }
        public string ShopMobile1 { get; set; }
        public string ShopEmail { get; set; }
        public string ShopWebSite { get; set; }
        public string ShopDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public Nullable<long> CreateUserID { get; set; }
        public Nullable<System.DateTime> InactivationDate { get; set; }
        public Nullable<long> InactivationUserID { get; set; }
        public string RegistrationNumber { get; set; }
        public string NationalID { get; set; }
        public Nullable<int> Fk_ProvinceID { get; set; }
        public Nullable<int> Fk_TownshipID { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<tbl_Sec_Users> tbl_Sec_Users { get; set; }
    }
}
