//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_src_FertilizerCategory
    {
        public tbl_src_FertilizerCategory()
        {
            this.tbl_src_Fertilizer = new HashSet<tbl_src_Fertilizer>();
        }
    
        public int FertilizerCategoryID { get; set; }
        public string NameEn { get; set; }
        public string NameFa { get; set; }
    
        public virtual ICollection<tbl_src_Fertilizer> tbl_src_Fertilizer { get; set; }
    }
}
