//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sec_Packages
    {
        public int PackageID { get; set; }
        public string PackageName { get; set; }
        public byte[] PackageLogo { get; set; }
        public int PackageOrder { get; set; }
        public Nullable<int> PackageFormsHeaderColor1 { get; set; }
        public Nullable<int> PackageFormsHeaderColor2 { get; set; }
    }
}
