//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_src_Tree
    {
        public int TreeID { get; set; }
        public Nullable<int> Fk_FieldID { get; set; }
        public Nullable<int> Fk_TreeType { get; set; }
        public string BaseCultivar { get; set; }
        public string BaseType { get; set; }
        public string ScionCultivar { get; set; }
        public Nullable<System.DateTime> DatePlanting { get; set; }
        public string SubInformation { get; set; }
        public string CantaminationHistory { get; set; }
        public string TreeYeild { get; set; }
        public Nullable<short> Row { get; set; }
        public Nullable<short> Column { get; set; }
        public string MainCultivar { get; set; }
        public string ScionLocation { get; set; }
        public string BaseBuyLocation { get; set; }
        public Nullable<System.DateTime> DateScion { get; set; }
        public string TransplantType { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> InactivationUserID { get; set; }
        public Nullable<System.DateTime> InactivationDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> Code { get; set; }
    }
}
