//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Per_PersonGroups
    {
        public int PersonGroupID { get; set; }
        public Nullable<int> FK_FactorCalculationTypeID { get; set; }
        public Nullable<int> PersonGroupCode { get; set; }
        public string PersonGroupName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> InactivationUserID { get; set; }
        public Nullable<System.DateTime> InactivationDate { get; set; }
    }
}
