//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_Goo_GoodsBasePriceOld
    {
        public int GoodBasePriceHID { get; set; }
        public Nullable<long> FK_GoodID { get; set; }
        public Nullable<long> FK_StoreID { get; set; }
        public long GoodBasePriceDID { get; set; }
        public Nullable<long> BasePrice { get; set; }
        public Nullable<long> FK_FactorDetailID { get; set; }
    }
}
