//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_Goo_GoodsUnit2QuantityRemainedWithBasePrice
    {
        public long GoodID { get; set; }
        public int StoreID { get; set; }
        public string StoreName { get; set; }
        public string GoodName { get; set; }
        public Nullable<decimal> IMP { get; set; }
        public Nullable<decimal> EXP { get; set; }
        public Nullable<decimal> RemaindUnit2Quantity { get; set; }
        public string MeasurmentUnit2 { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
    }
}
