//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viw_Saf_Reason
    {
        public long ReasonID { get; set; }
        public string SafeReasonTypeName { get; set; }
        public string SafeReasonName { get; set; }
        public Nullable<int> FK_SafeReasonTypeID { get; set; }
        public Nullable<long> FK_SafeReasonID { get; set; }
        public long SafeID { get; set; }
    }
}
