//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_Part_Location
    {
        public string PartName { get; set; }
        public string SubCollectionName { get; set; }
        public string CollectionName { get; set; }
        public string ProvinceName { get; set; }
        public string TownshipName { get; set; }
        public System.Data.Spatial.DbGeometry Location { get; set; }
        public int PartID { get; set; }
        public int SubCollectionID { get; set; }
        public int CollectionID { get; set; }
    }
}
