//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viw_Saf_SumRecievePayemtByFactorNumber
    {
        public int FK_FactorOperationTypeID { get; set; }
        public Nullable<int> FK_StoreID { get; set; }
        public Nullable<long> SumCashAmount { get; set; }
        public Nullable<long> SumChequeAmount { get; set; }
        public Nullable<long> SumPosAmoun { get; set; }
        public long FactorID { get; set; }
    }
}
