//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BaranResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaranResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Baran.BaranResources", typeof(BaranResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکالی در برقراری ارتباط با سرور رخ داده است لطفا بعدا دوباره تلاش کنید .
        /// </summary>
        internal static string AccessibleItemsInsertionInDBError {
            get {
                return ResourceManager.GetString("AccessibleItemsInsertionInDBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار.
        /// </summary>
        internal static string ainFormClosingMessageBoxCaption {
            get {
                return ResourceManager.GetString("ainFormClosingMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاکتوری با شماره ای که مشخص کرده اید موجود نمی باشد..
        /// </summary>
        internal static string AppendixIsNotLegitimate {
            get {
                return ResourceManager.GetString("AppendixIsNotLegitimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ چک را وارد نکرده اید.
        /// </summary>
        internal static string ChequeAmountIsNotSpecified {
            get {
                return ResourceManager.GetString("ChequeAmountIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عهده بانک واگذار شده را وارد نکرده اید.
        /// </summary>
        internal static string ChequeBankAccountHandOverIsNotSpecified {
            get {
                return ResourceManager.GetString("ChequeBankAccountHandOverIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چک قبلا نقد شده است ، امکان تغییر وجود ندارد.
        /// </summary>
        internal static string ChequeCashedLastTimeEditDoNot {
            get {
                return ResourceManager.GetString("ChequeCashedLastTimeEditDoNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چک قبلا وصول شده است ، امکان تغییر وجود ندارد.
        /// </summary>
        internal static string ChequeCollectedLastTimeEditDoNot {
            get {
                return ResourceManager.GetString("ChequeCollectedLastTimeEditDoNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چک قبلا واگذار شده است ، امکان تغییر وجود ندارد.
        /// </summary>
        internal static string ChequeHnadOveredLastTimeEditDoNot {
            get {
                return ResourceManager.GetString("ChequeHnadOveredLastTimeEditDoNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان وصول چک قبل از تارخ سر رسید چک وجود ندارد.
        /// </summary>
        internal static string ChequeMatureDateDontArrivedCanNotCollected {
            get {
                return ResourceManager.GetString("ChequeMatureDateDontArrivedCanNotCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ سررسید چک را وارد نکرده اید.
        /// </summary>
        internal static string ChequeMatureDateIsNotSpecified {
            get {
                return ResourceManager.GetString("ChequeMatureDateIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره چک را وارد نکرده اید.
        /// </summary>
        internal static string ChequeNumberIsNotSpecified {
            get {
                return ResourceManager.GetString("ChequeNumberIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعبه بانکی را که چک را صادر کرده است را وارد نکرده اید.
        /// </summary>
        internal static string ChequeRelatedBankBranchIsNotSpecified {
            get {
                return ResourceManager.GetString("ChequeRelatedBankBranchIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک صادر کننده چک را وارد نکرده اید.
        /// </summary>
        internal static string ChequeRelatedBankIsNotSpecified {
            get {
                return ResourceManager.GetString("ChequeRelatedBankIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چک قبلا برگشت داده شده است، امکان تغییر وجود ندارد.
        /// </summary>
        internal static string ChequeRollBackLastTimeEditDoNot {
            get {
                return ResourceManager.GetString("ChequeRollBackLastTimeEditDoNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چک قبلا خرج شده است، امکان تغییر وجود ندارد.
        /// </summary>
        internal static string ChequeSpendedLastTimeEditDoNot {
            get {
                return ResourceManager.GetString("ChequeSpendedLastTimeEditDoNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکالی در برقراری ارتباط با سرور روی داده است لطفا بعدا دوباره تلاش نمایید یا با پشتیبانی تماس بگیرید.
        /// </summary>
        internal static string ConnectionWithServerError {
            get {
                return ResourceManager.GetString("ConnectionWithServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا هنگام خواندن فایل.
        /// </summary>
        internal static string CouldNotReadFileFromDisk {
            get {
                return ResourceManager.GetString("CouldNotReadFileFromDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.0.0.0.
        /// </summary>
        internal static string CrossCheckForVersionNumber {
            get {
                return ResourceManager.GetString("CrossCheckForVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره چک را وارد نکرده اید.
        /// </summary>
        internal static string CustomerChequeNumberIsNotSpecified {
            get {
                return ResourceManager.GetString("CustomerChequeNumberIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ نا معتبر می باشد.
        /// </summary>
        internal static string DateInvalid {
            get {
                return ResourceManager.GetString("DateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف اطلاعات برای نوع کاربری شما تعریف نشده است.
        /// </summary>
        internal static string DeleteAccessDenied {
            get {
                return ResourceManager.GetString("DeleteAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف اطلاعات در سال مالی قبل وجود ندارد.
        /// </summary>
        internal static string DeleteAccessDeniedInUnCurrentFiscalYear {
            get {
                return ResourceManager.GetString("DeleteAccessDeniedInUnCurrentFiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?آیا از حذف اطلاعات اطمینان دارید.
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا عملیات حذف انجام شده است.
        /// </summary>
        internal static string DeletedLastTime {
            get {
                return ResourceManager.GetString("DeletedLastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در حذف اطلاعات.
        /// </summary>
        internal static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف اطلاعات با موفقیت انجام شد.
        /// </summary>
        internal static string DeleteSuccessful {
            get {
                return ResourceManager.GetString("DeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه دسترسی به این بخش را ندارید.
        /// </summary>
        internal static string DonNotHavePermission {
            get {
                return ResourceManager.GetString("DonNotHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام نشد! لطفا دوباره تلاش نمایید.
        /// </summary>
        internal static string DoNotDoPleaseTryAgine {
            get {
                return ResourceManager.GetString("DoNotDoPleaseTryAgine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان چاپ المثنی برای فاکتور امکان پذیر نمی باشد.
        /// </summary>
        internal static string DublicatePrintAccessDenied {
            get {
                return ResourceManager.GetString("DublicatePrintAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا کالایی با این نام ثبت شده است.
        /// </summary>
        internal static string DuplicateGoodName {
            get {
                return ResourceManager.GetString("DuplicateGoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا کاربری با این نام کاربری تعریف شده است لطفا نام کاربری دیگری را انتخاب نمایید..
        /// </summary>
        internal static string DuplicateUsererrorMessage {
            get {
                return ResourceManager.GetString("DuplicateUsererrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تغییراطلاعات برای نوع کاربری شما تعریف نشده است.
        /// </summary>
        internal static string EditAccessDenied {
            get {
                return ResourceManager.GetString("EditAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تغییر اطلاعات در سال مالی قبل وجود ندارد.
        /// </summary>
        internal static string EditAccessDeniedInUnCurrentFiscalYear {
            get {
                return ResourceManager.GetString("EditAccessDeniedInUnCurrentFiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا تغییرات اعمال شود.
        /// </summary>
        internal static string EditConfirm {
            get {
                return ResourceManager.GetString("EditConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تغییر اطلاعات وجود ندارد.
        /// </summary>
        internal static string EditDoNot {
            get {
                return ResourceManager.GetString("EditDoNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در تغییر اطلاعات.
        /// </summary>
        internal static string EditFail {
            get {
                return ResourceManager.GetString("EditFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییراطلاعات با موفقیت انجام شد.
        /// </summary>
        internal static string EditSuccessful {
            get {
                return ResourceManager.GetString("EditSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی خود را وارد نکرده اید.
        /// </summary>
        internal static string FamilyTextBoxIsEmptyMessage {
            get {
                return ResourceManager.GetString("FamilyTextBoxIsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا اطلاعات را کامل وارد نمایید.
        /// </summary>
        internal static string FeildIsEmpty {
            get {
                return ResourceManager.GetString("FeildIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکالی در هنگام دریافت کالا ها از سرور روی داده است لطفا دوباره تلاش کنید یا با پشتیبانی تماس بگیرید.
        /// </summary>
        internal static string FetchingGoodsFromDBError {
            get {
                return ResourceManager.GetString("FetchingGoodsFromDBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل از قبل وجود دارد، آیا می خواهید جایگزین کنید؟.
        /// </summary>
        internal static string FileAlreadyExistsDoYouWantToReplace {
            get {
                return ResourceManager.GetString("FileAlreadyExistsDoYouWantToReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت خرید کالا را وارد نکرده اید.
        /// </summary>
        internal static string GoodBuyPriceIsNotSpecified {
            get {
                return ResourceManager.GetString("GoodBuyPriceIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت فروش نقدی کالا را وارد نکرده اید.
        /// </summary>
        internal static string GoodCashSalePriceIsNotSpecified {
            get {
                return ResourceManager.GetString("GoodCashSalePriceIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت فروش چکی کالا را مشخص نکرده اید.
        /// </summary>
        internal static string GoodChequeSalePriceIsNotSpecified {
            get {
                return ResourceManager.GetString("GoodChequeSalePriceIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالایی با این نام قبلا تعریف شده است.
        /// </summary>
        internal static string GoodIsDefinedBeforeError {
            get {
                return ResourceManager.GetString("GoodIsDefinedBeforeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما کالایی را انتخاب نکرده اید ابتدا کالا را انتخاب نمایید و سپس تعداد آن را مشخص نمایید تا زمانی که کالایی را مشخص نکنید ضریب تبدیل بین واحد های آن نیز مشخص نخواهد بود .
        /// </summary>
        internal static string GoodIsNotSelected {
            get {
                return ResourceManager.GetString("GoodIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت فروش متفرقه کالا را وارد نکرده اید.
        /// </summary>
        internal static string GoodMotefaregheSalePriceIsNotSpecified {
            get {
                return ResourceManager.GetString("GoodMotefaregheSalePriceIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کالا را وارد نکرده اید.
        /// </summary>
        internal static string GoodNameIsNotSpecified {
            get {
                return ResourceManager.GetString("GoodNameIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکال در به هتگام رسانی کالا لطفا دوباره تلاش کنید یا با پشتیبانی تماس بگیرید.
        /// </summary>
        internal static string GoodUpdateError {
            get {
                return ResourceManager.GetString("GoodUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالای مدنظر شما با موفقیت به هنگام رسانده شد.
        /// </summary>
        internal static string GoodUpdateIsSuccessful {
            get {
                return ResourceManager.GetString("GoodUpdateIsSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم عکس بالا می باشد، باید کمتر از 300 کیلوبایت باشد.
        /// </summary>
        internal static string ImageSizeIsHigh {
            get {
                return ResourceManager.GetString("ImageSizeIsHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و یا رمز عبور را اشتباه وارد کرده اید.
        /// </summary>
        internal static string invalidCredentialsAtLogin {
            get {
                return ResourceManager.GetString("invalidCredentialsAtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نرم افزار برای استفاده توسط شما تنظیم نگردیده است.
        /// </summary>
        internal static string LegitimationErrorMessage {
            get {
                return ResourceManager.GetString("LegitimationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکال در مجوز استفاده از نرم افزار.
        /// </summary>
        internal static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به سیستم حسابداری دامون خوش آمدید.
        /// </summary>
        internal static string LoginFormCaption {
            get {
                return ResourceManager.GetString("LoginFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از خروج اطمینان دارید.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا می خواهید از برنامه خارج شوید؟.
        /// </summary>
        internal static string MainFormClosingMessage {
            get {
                return ResourceManager.GetString("MainFormClosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف اعتبار چکی را منفی وارد کرده اید.
        /// </summary>
        internal static string MaxChequeCreditIsNegativeError {
            get {
                return ResourceManager.GetString("MaxChequeCreditIsNegativeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف اعتبار بستانکاری را منفی وارد کرده اید!.
        /// </summary>
        internal static string MaxCreditIsNegativeError {
            get {
                return ResourceManager.GetString("MaxCreditIsNegativeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف اعتبار بدهکاری را منفی وارد کرده اید.
        /// </summary>
        internal static string MaxDebitIsNegativeError {
            get {
                return ResourceManager.GetString("MaxDebitIsNegativeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد اندازه گیری اول را وارد نکرده اید.
        /// </summary>
        internal static string MeasurementUnit1IsNotSpecified {
            get {
                return ResourceManager.GetString("MeasurementUnit1IsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد اندازه گیری دوم را وارد نکرده اید.
        /// </summary>
        internal static string MeasurementUnit2IsNotSpecified {
            get {
                return ResourceManager.GetString("MeasurementUnit2IsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خود را وارد نکرده اید.
        /// </summary>
        internal static string NameTextBoxIsEmptyMessage {
            get {
                return ResourceManager.GetString("NameTextBoxIsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تعریف جدید اطلاعات برای نوع کاربری شما تعریف نشده است.
        /// </summary>
        internal static string NewAccessDenied {
            get {
                return ResourceManager.GetString("NewAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشتباهی در هنگام تعریف کالا روی داده است لطفا بعدا دوباره سعی نمایید یا با پشتیبانی تماس حاصل نمایید.
        /// </summary>
        internal static string NewGoodInsertionInDBError {
            get {
                return ResourceManager.GetString("NewGoodInsertionInDBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالای جدید با موفقیت تعریف گردید.
        /// </summary>
        internal static string NewGoodInsertionInDBIsSuccessfulMessage {
            get {
                return ResourceManager.GetString("NewGoodInsertionInDBIsSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید را به درستی تکرار نکرده اید.
        /// </summary>
        internal static string newPasswordConfirmationError {
            get {
                return ResourceManager.GetString("newPasswordConfirmationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز جدید مد نظر خود را وارد نکرده اید.
        /// </summary>
        internal static string NewPasswordnotSpecifiedError {
            get {
                return ResourceManager.GetString("NewPasswordnotSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص جدید با موفقیت تعریف گردید.
        /// </summary>
        internal static string newPersonInsertionSuccessfulMessage {
            get {
                return ResourceManager.GetString("newPersonInsertionSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکالی در برقراری ارتباط با سرور رخ داده است لطفا بعدا دوباره تلاش نمایید.
        /// </summary>
        internal static string NewUserInsertionInDBError {
            get {
                return ResourceManager.GetString("NewUserInsertionInDBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کالایی را برای ثبت در فاکتور انتخاب نمایید.
        /// </summary>
        internal static string NoGoodInBuyFactorError {
            get {
                return ResourceManager.GetString("NoGoodInBuyFactorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ آیتمی انتخاب نشده است.
        /// </summary>
        internal static string NoItemsSelected {
            get {
                return ResourceManager.GetString("NoItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نوع پرداخت فاکتور را مشخص نمایید.
        /// </summary>
        internal static string NoPaymentMethodSpecified {
            get {
                return ResourceManager.GetString("NoPaymentMethodSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخصی با نام و نام خانوادگی مشخص شده یافت نشد.
        /// </summary>
        internal static string NoPersonFound {
            get {
                return ResourceManager.GetString("NoPersonFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک سطر را انتخاب نمایید.
        /// </summary>
        internal static string NoRowSelectedError {
            get {
                return ResourceManager.GetString("NoRowSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای کالای کنونی قبلا موجودی تعریف نگردیده است.
        /// </summary>
        internal static string NoStockInfoAvailableForCurrentGood {
            get {
                return ResourceManager.GetString("NoStockInfoAvailableForCurrentGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string numberofPackegsInSystem {
            get {
                return ResourceManager.GetString("numberofPackegsInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پارتیشن را تعریف نکرده اید.
        /// </summary>
        internal static string PartitionNameIsEmpty {
            get {
                return ResourceManager.GetString("PartitionNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکالی در هنگام تعویض رمز عبور پیش آمده است لطفا با پشتیبانی تماس بگیرید.
        /// </summary>
        internal static string passwordChangeErrorMessage {
            get {
                return ResourceManager.GetString("passwordChangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکال در تایید رمز عبور.
        /// </summary>
        internal static string PasswordConfirmationError {
            get {
                return ResourceManager.GetString("PasswordConfirmationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور قبلی خود را اشتباه وارد کرده اید.
        /// </summary>
        internal static string PasswordIncorrectInFrmChangePassword {
            get {
                return ResourceManager.GetString("PasswordIncorrectInFrmChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور خود را وارد نکرده اید.
        /// </summary>
        internal static string PasswordTextBoxIsEmptyMessage {
            get {
                return ResourceManager.GetString("PasswordTextBoxIsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص مورد نظر با موفقیت حذف گردید..
        /// </summary>
        internal static string PersonDeletionIsCompletedSuccessfully {
            get {
                return ResourceManager.GetString("PersonDeletionIsCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی شخص را وارد نکرده اید.
        /// </summary>
        internal static string PersonFamilyIsNotSpecified {
            get {
                return ResourceManager.GetString("PersonFamilyIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی شخص را وارد نکرده اید.
        /// </summary>
        internal static string PersonFamilyTextBoxIsEmptyError {
            get {
                return ResourceManager.GetString("PersonFamilyTextBoxIsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و یا نام خانوادگی و یا هر دو تکراری می باشند.
        /// </summary>
        internal static string PersonIsDuplicateError {
            get {
                return ResourceManager.GetString("PersonIsDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شخص را وارد نکرده اید.
        /// </summary>
        internal static string PersonNameIsNotSpecified {
            get {
                return ResourceManager.GetString("PersonNameIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شخص را وارد نکرده اید.
        /// </summary>
        internal static string personNameTextBoxISEmptyerror {
            get {
                return ResourceManager.GetString("personNameTextBoxISEmptyerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص مورد نظر با موفقیت به هنگام رسانده شد.
        /// </summary>
        internal static string PersonUpdateSuccessful {
            get {
                return ResourceManager.GetString("PersonUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مقادیر را وارد نمایید.
        /// </summary>
        internal static string PleaseComplateFeilds {
            get {
                return ResourceManager.GetString("PleaseComplateFeilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقطه سفارش را مشخص نکرده اید.
        /// </summary>
        internal static string PointOfReOrderIsNotSpecified {
            get {
                return ResourceManager.GetString("PointOfReOrderIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدا کارت را کشیده و سپس دکمه اتصال به دستگاه را کلیک کنید.
        /// </summary>
        internal static string PosTakeCardAndClickConnectToPos {
            get {
                return ResourceManager.GetString("PosTakeCardAndClickConnectToPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان پرینت اطلاعات برای نوع کاربری شما تعریف نشده است.
        /// </summary>
        internal static string PrintAccessDenied {
            get {
                return ResourceManager.GetString("PrintAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا پرینت گرفته شود؟.
        /// </summary>
        internal static string PrintConfirm {
            get {
                return ResourceManager.GetString("PrintConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ارسال پرینت.
        /// </summary>
        internal static string PrintFail {
            get {
                return ResourceManager.GetString("PrintFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرینت گرفته شد.
        /// </summary>
        internal static string PrintSuccessful {
            get {
                return ResourceManager.GetString("PrintSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد با واحد یک را مشخص نکرده اید.
        /// </summary>
        internal static string Quantity1IsEmpty {
            get {
                return ResourceManager.GetString("Quantity1IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد با واحد دو را مشخص نکرده اید.
        /// </summary>
        internal static string Quantity2IsEmpty {
            get {
                return ResourceManager.GetString("Quantity2IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فیش و حواله شما با موفقیت ثبت گردید.
        /// </summary>
        internal static string receiptsAddedSuccessfully {
            get {
                return ResourceManager.GetString("receiptsAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ فیش یا حواله را وارد نکرده اید.
        /// </summary>
        internal static string RecieptAssAmounIsNotSpecified {
            get {
                return ResourceManager.GetString("RecieptAssAmounIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شعبه صادر کننده فیش یا حواله را وارد نکرده اید.
        /// </summary>
        internal static string RecieptAssBankBranchIsNotSpecified {
            get {
                return ResourceManager.GetString("RecieptAssBankBranchIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  نام بانک صادر کننده فیش یا حواله را وارد نکرده اید.
        /// </summary>
        internal static string RecieptAssBankIsNotSpecified {
            get {
                return ResourceManager.GetString("RecieptAssBankIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پرداخت فیش یا حواله را وارد نکرده اید.
        /// </summary>
        internal static string RecieptAssDateIsNotSpecified {
            get {
                return ResourceManager.GetString("RecieptAssDateIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فیش یا حواله را وارد نکرده اید.
        /// </summary>
        internal static string RecieptAssNumberIsNotSpecified {
            get {
                return ResourceManager.GetString("RecieptAssNumberIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا شخصی را که چک را از او دریافت می نمایید را مشخص کنید.
        /// </summary>
        internal static string RecievedFromIsEmpty {
            get {
                return ResourceManager.GetString("RecievedFromIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ رکوردی یافت نشد.
        /// </summary>
        internal static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا به بخش مربوطه مراجعه نمایید.
        /// </summary>
        internal static string ReferToRelevantSection {
            get {
                return ResourceManager.GetString("ReferToRelevantSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع چاپ فاکتور تنظیم نشده است.
        /// </summary>
        internal static string ReportSettingPageSizeNotSet {
            get {
                return ResourceManager.GetString("ReportSettingPageSizeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فاکتور برگشت خالی میباشد.
        /// </summary>
        internal static string ReturnFactorNumberIsEmpty {
            get {
                return ResourceManager.GetString("ReturnFactorNumberIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت اطلاعات برای نوع کاربری شما تعریف نشده است .
        /// </summary>
        internal static string SaveAccessDenied {
            get {
                return ResourceManager.GetString("SaveAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت اطلاعات در سال مالی قبل وجود ندارد.
        /// </summary>
        internal static string SaveAccessDeniedInUnCurrentFiscalYear {
            get {
                return ResourceManager.GetString("SaveAccessDeniedInUnCurrentFiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ? آیا اطلاعات ثبت شود.
        /// </summary>
        internal static string SaveConfirm {
            get {
                return ResourceManager.GetString("SaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فبلا اطلاعات ثبت شده است.
        /// </summary>
        internal static string SavedLastTime {
            get {
                return ResourceManager.GetString("SavedLastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات قبلا ثبت شده است، آیا می خواهید تغییرات بر روی آن اعمال شود.
        /// </summary>
        internal static string SavedLastTimeDoYouWantEditConfirm {
            get {
                return ResourceManager.GetString("SavedLastTimeDoYouWantEditConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات قبلا برای این حساب بانکی تعریف شده است برای اعمال تغییرات از دکمه تغییر استفاده نمایید.
        /// </summary>
        internal static string SavedLastTimeForThisBankAccountChangeConfirm {
            get {
                return ResourceManager.GetString("SavedLastTimeForThisBankAccountChangeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا اطلاعات ثبت نشده است.
        /// </summary>
        internal static string SavedNotLastTime {
            get {
                return ResourceManager.GetString("SavedNotLastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت اطلاعات تکراری وجود ندارد.
        /// </summary>
        internal static string SaveDuplicateKeyError {
            get {
                return ResourceManager.GetString("SaveDuplicateKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! خطا در ثبت اطلاعات.
        /// </summary>
        internal static string SaveFail {
            get {
                return ResourceManager.GetString("SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات قبلا ثبت نشده است، آیا اطلاعات ثبت شود.
        /// </summary>
        internal static string SaveNotLastTimeSaveConfirm {
            get {
                return ResourceManager.GetString("SaveNotLastTimeSaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت ثبت شد.
        /// </summary>
        internal static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopCode.
        /// </summary>
        internal static string ShopTableShopCodeColumn {
            get {
                return ResourceManager.GetString("ShopTableShopCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام انبار را وارد نکرده اید.
        /// </summary>
        internal static string StoreNameIsEmpty {
            get {
                return ResourceManager.GetString("StoreNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغیر رمز به درستی انجام شد.
        /// </summary>
        internal static string SuccessfulPasswordChangeMessage {
            get {
                return ResourceManager.GetString("SuccessfulPasswordChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر جدید با موفقیت تعریف گردید.
        /// </summary>
        internal static string SuccessfulUserDefinition {
            get {
                return ResourceManager.GetString("SuccessfulUserDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالایی با نام مشخص شده یافت نشد.
        /// </summary>
        internal static string TheSpecifiedGoodNotFound {
            get {
                return ResourceManager.GetString("TheSpecifiedGoodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این بخش در حال ایجاد شدن است.
        /// </summary>
        internal static string UnderConstructionErrorMessage {
            get {
                return ResourceManager.GetString("UnderConstructionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد با واحد یک را مشخص نکرده اید.
        /// </summary>
        internal static string Unit1IsNotSpecified {
            get {
                return ResourceManager.GetString("Unit1IsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضریب تبدیل بین واحد ها را وارد نکرده اید.
        /// </summary>
        internal static string UnitsConversionCoefficientIsNotSpecified {
            get {
                return ResourceManager.GetString("UnitsConversionCoefficientIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف کاربر با موفقیت به هنگام رسانده شد.
        /// </summary>
        internal static string UserDefinintionUpdateSuccessful {
            get {
                return ResourceManager.GetString("UserDefinintionUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه می باشد.
        /// </summary>
        internal static string UserNameOrPasswordIsWrong {
            get {
                return ResourceManager.GetString("UserNameOrPasswordIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری خود را وارد نکرده اید.
        /// </summary>
        internal static string UserNameTextBoxIsEmptyMessage {
            get {
                return ResourceManager.GetString("UserNameTextBoxIsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ShopID.
        /// </summary>
        internal static string UserTableFK_ShopIDColumn {
            get {
                return ResourceManager.GetString("UserTableFK_ShopIDColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID.
        /// </summary>
        internal static string UserTableUserIDColumn {
            get {
                return ResourceManager.GetString("UserTableUserIDColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربر تغییر یافت اما سطح دسترسی تغییر نکرد، لطفا مجددا تلاش کنید.
        /// </summary>
        internal static string UserUpdatedButItemsCannotBeUpdated {
            get {
                return ResourceManager.GetString("UserUpdatedButItemsCannotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورژن برنامه تغیر کرده است، آیا برنامه بروزرسانی شود؟ در صورت بروز مشکل با پشتیبانی 09195665573 تماس بگیرید /n  آیا برنامه بروزرسانی شود؟.
        /// </summary>
        internal static string VersionErrorMessage {
            get {
                return ResourceManager.GetString("VersionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گروه ویزیت را مشخص نکرده اید.
        /// </summary>
        internal static string VisitGroupNameISNotSelected {
            get {
                return ResourceManager.GetString("VisitGroupNameISNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد ویزیتور برای این کالا را مشخص نکرده اید.
        /// </summary>
        internal static string visitorPercentageIsnotSpecified {
            get {
                return ResourceManager.GetString("visitorPercentageIsnotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سفته تکراری است.
        /// </summary>
        internal static string warrabtyNumberIsDuplicateError {
            get {
                return ResourceManager.GetString("warrabtyNumberIsDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ سفته را منفی وارد کرده اید.
        /// </summary>
        internal static string WarrantyAmountIsNegativeError {
            get {
                return ResourceManager.GetString("WarrantyAmountIsNegativeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ سفته را وارد نکرده اید.
        /// </summary>
        internal static string WarrantyAmountISNotSpecified {
            get {
                return ResourceManager.GetString("WarrantyAmountISNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سفته را وارد نکرده اید.
        /// </summary>
        internal static string warrantyNumberIsNotSpecified {
            get {
                return ResourceManager.GetString("warrantyNumberIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف کاربری که با آن وارد سیستم شده اید را ندارید.
        /// </summary>
        internal static string YouCannotDeleteTheCurrentUuser {
            get {
                return ResourceManager.GetString("YouCannotDeleteTheCurrentUuser", resourceCulture);
            }
        }
    }
}
