//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaranLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BaranLibraryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaranLibraryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaranLibrary.BaranLibraryResources", typeof(BaranLibraryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف اطلاعات برای نوع کاربری شما تعریف نشده است.
        /// </summary>
        internal static string DeleteAccessDenied {
            get {
                return ResourceManager.GetString("DeleteAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف اطلاعات در سال مالی قبل وجود ندارد.
        /// </summary>
        internal static string DeleteAccessDeniedInUnCurrentFiscalYear {
            get {
                return ResourceManager.GetString("DeleteAccessDeniedInUnCurrentFiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?آیا از حذف اطلاعات اطمینان دارید.
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا عملیات حذف انجام شده است.
        /// </summary>
        internal static string DeletedLastTime {
            get {
                return ResourceManager.GetString("DeletedLastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در حذف اطلاعات.
        /// </summary>
        internal static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف اطلاعات با موفقیت انجام شد.
        /// </summary>
        internal static string DeleteSuccessful {
            get {
                return ResourceManager.GetString("DeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تغییراطلاعات برای نوع کاربری شما تعریف نشده است.
        /// </summary>
        internal static string EditAccessDenied {
            get {
                return ResourceManager.GetString("EditAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تغییر اطلاعات در سال مالی قبل وجود ندارد.
        /// </summary>
        internal static string EditAccessDeniedInUnCurrentFiscalYear {
            get {
                return ResourceManager.GetString("EditAccessDeniedInUnCurrentFiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا تغییرات اعمال شود.
        /// </summary>
        internal static string EditConfirm {
            get {
                return ResourceManager.GetString("EditConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تغییر اطلاعات وجود ندارد.
        /// </summary>
        internal static string EditDoNot {
            get {
                return ResourceManager.GetString("EditDoNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در تغییر اطلاعات.
        /// </summary>
        internal static string EditFail {
            get {
                return ResourceManager.GetString("EditFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییراطلاعات با موفقیت انجام شد.
        /// </summary>
        internal static string EditSuccessful {
            get {
                return ResourceManager.GetString("EditSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اطلاعات ثبت شود.
        /// </summary>
        internal static string SaveConfirm {
            get {
                return ResourceManager.GetString("SaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت اطاعات.
        /// </summary>
        internal static string SaveFail {
            get {
                return ResourceManager.GetString("SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات با موفقیت انجام شد.
        /// </summary>
        internal static string SaveSucessful {
            get {
                return ResourceManager.GetString("SaveSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز را وارد نکرده اید.
        /// </summary>
        internal static string txtDayIsEmpty {
            get {
                return ResourceManager.GetString("txtDayIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای روز یک عدد وارد نمایید.
        /// </summary>
        internal static string txtDayIsNotInteger {
            get {
                return ResourceManager.GetString("txtDayIsNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه را وارد نکرده اید.
        /// </summary>
        internal static string txtMonthIsEmpty {
            get {
                return ResourceManager.GetString("txtMonthIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ماه یک عدد وارد نمایید.
        /// </summary>
        internal static string txtMonthIsNotInteger {
            get {
                return ResourceManager.GetString("txtMonthIsNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال را وارد نکرده اید.
        /// </summary>
        internal static string txtYearIsEmpty {
            get {
                return ResourceManager.GetString("txtYearIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای سال یک عدد وارد نمایید.
        /// </summary>
        internal static string txtYearIsNotInteger {
            get {
                return ResourceManager.GetString("txtYearIsNotInteger", resourceCulture);
            }
        }
    }
}
